### ISSUE TITLE
temperature in toml

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#32]
The temperature is defined in hard code `0.2`, we need to take it to the configuration (in TOML), making the project customizable

https://github.com/talkdai/dialog/blob/012c73c02b30382d3dd95068dd0255e1242d8789/src/llm/__init__.py#L23

```toml
[prompt]
temperature = 0.2
```

> if not set, it should be temperature `0.2` by default

**Comment by lgabs** [comment]
Maybe I can take this one to get used to the project :) 

Is there a specific reason for choosing 0.2? Not that the default would matter to much since each project user will have to test some values, but in a Q&A setting, I thought it might be preferable to select 0, as it is the minimum value and helps to minimize randomness (0 would give almost the same results for the same prompt). Of course there isn't a unique answer, but I saw briefly some discussion [here, suggesting 0.2 for chatbot](https://community.openai.com/t/cheat-sheet-mastering-temperature-and-top-p-in-chatgpt-api-a-few-tips-and-tricks-on-controlling-the-creativity-deterministic-output-of-prompt-responses/172683) and [here](https://community.openai.com/t/is-the-lower-the-temperature-the-more-correct-the-answer-is/316029).

**Comment by avelino** [comment]
> Generates data analysis scripts that are more likely to be correct and efficient. Output is more deterministic and focused.

@lgabs thinking about a **humanized conversation**, I believe it's important to have answers that are _"likely to be correct and efficient"_, which is why I believe `0.2` should be our standard thermometer, but with support for the user to change the settings.
