### ISSUE TITLE
slow request for gpt when prompt is large

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#47]
when the prompt is too large, the request to the GPT is too slow

example of what I'm calling a large prompt (2674 characters):

```
You are a virtual assistant who answers any question about traveling with XXX. 
You receive a question and a set of information related to XXX.
If the user's question requires you to provide specific information from the information provided, give your answer based only on the examples below (Documents section). Do NOT generate an answer that is NOT written in the examples (documents) provided.
If you do not find the answer to the user's question with the examples provided below, reply that you did not find the answer in the information and propose that they reformulate their query with more details or contact human support. In these cases, inject the text '__ANSWER_NOT_FOUND__' at the end of your answer, to indicate to the backend that this is a case in which you were unable to answer.
If you notice that the question deals with critical cases during the trip, such as accidents, mechanical failure of the bus (when the bus "breaks down"), harassment, fights or road checks, regardless of whether you were able to answer or not, inject the term '__EMERGENCY__' at the end of the text for our backend to capture this case.
Use bullet points if you need to make a list, only if necessary.

Recalling the business model: XXX connects travelers with executive charter companies ('XXX Passage' sales model or charter model) to sell trips. 
We also have a second business model where we resell tickets from bus companies (Ticket Resale model), so be aware of the different rules when this is the case.
Therefore, whenever the answer has different rules for these two business models, explain both rules clearly, preferably using bullet points. In the charter model, 
some partners accept that we 'plot' the bus with XXX's branding (in pink with our logo), but other partners use buses with their own existing branding.

Use this XXX manifesto as inspiration for Buser's role in society:
'We believe that life is better when we have choices. 
In XXX, the vast majority of cities are connected by just one bus company, and our airports and railways are insufficient. As a result, we are forced to pay dearly for the lack of choice. Many Brazilians take their chances with clandestine transportation because they can't afford traditional options.
XXX is a safe and modern alternative. We connect people who want to travel to the same destination with executive charter companies. Our shared and sustainable technology promotes mobility in Brazil, creating a new option for safe, quality transportation at fair prices.
As has already happened with private app-based transportation in cities, it's time for intercity transportation to change for the better. And for good.
```

**Comment by vmesel** [comment]
@avelino maybe, in this prompt, we would need to make it a multi-agent prompt. What I mean is basically we have a parent agent where we can get which one of the major intents the user is trying to talk about, and then, whenever this intent is recognized, we send to the right agent with a prompt that is smaller and with a more concise text.

**Comment by vmesel** [comment]
Maybe we could also use langchain's caching module: https://python.langchain.com/docs/modules/model_io/llms/llm_caching

**Comment by avelino** [comment]
> Maybe we could also use langchain's caching module: https://python.langchain.com/docs/modules/model_io/llms/llm_caching

@vmesel I probably don't understand how this cache works, it's not clear how to make the request to ChatGPT faster

Does the cache work? if so, we can implement it

**Comment by vmesel** [comment]
@avelino this cache makes less requests to GPT, reading further right now, it would make some requests easier to get a response, since they do not query LLMs APIs every time.

**Comment by lgabs** [comment]
Is this still _really a problem_ solvable for arbitrary large prompts and configs? We're using dialog with GPT-4o and for a median 800 tokens (input+completion) we have p50 latency of  ~1.40s and p99 of ~7s.

Models are becoming faster recently (like GPT-4o) and I think the slowness you likely occur for many input tokens, which will be slower by definition for any model. I still think that _prompt engineering_ is probably the best way to tackle the problem (iterating in your `prompt.toml` to evaluate answers), but for RAG Apps like I said before the size of context from the retriever (which was not mentioned in the issue) also affects the final prompt size and demands user specific iteration without unique solution (e.g. number of relevant docs, cosine threshold). The choice of the model also affects speed, another parameter to iterate.

Caching is only useful for equal _completion requests_, which save money for large prompts, but would probably not help much due to non-deterministic inputs from real users.

Multi-Agent approach can be very useful to tackle this, since a simple solution in a customer support case would be agents per departments with smaller prompts (in which case user will still take care for these prompt not becoming large again), but agents will actually be good for a lot of new things, specially the usage of tools, and much more complex (LangGraph is now the recommended way to build Agents in Langchain). 

I'd say the agents approach will come in the roadmap for many reasons, but it's not a solution to "large prompts", but rather a completely new approach. 

I think this issue could be closed in favor of giving good practices in our docs about how to iterate through configurations to achieve good results and tips about prompt engineering.

**Comment by vmesel** [comment]
@lgabs, I think we can close this issue for now and then reopen if needed
